####
## @file
## Jekyll configuration
##
## We try to push as much sitewide config as possible into this file, so a new deployment can start with just editing
## this file.
##
## If you need help with YAML syntax, here are some quick references for you:
## https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
## https://learnxinyminutes.com/docs/yaml/
##
## Throughout this file, you'll see two # marks at the start of a line for a permanent comment, and a single # for
## configuration options that can be enabled by removing the #.
##
## When adding new sections, be sure to name them so they make sense to others, and to document with good comments
## wherever possible/practical.
####

markdown: rdiscount
permalink: /:year/:month/:title/
highlighter: pygments
rdiscount:
  extensions: [smart]
sass:
  style: :compressed
gems:
  - jekyll-sitemap

## Site structure
collections:
  recipes:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
      schema: Recipe

## Basic site info
title: "Sharon's Cookbook"
primary_author: "Sharon Turner"
shortname: Sharon
# subpath should include leading slash or be an empty string
subpath: /turner-cookbook
source_repo: http://www.github.com/ao5357/turner-cookbook
email: ao5357@gmail.com
phone: 248-721-0350
gaid: UA-697953-3

## schema.org type (default for site, often "Website")
schema: Book

## Open Graph
og_street_address: 1428 Mark Ave
og_locality: Lincoln Park
og_region: MI
og_postal_code: "48146"
og_country: USA
